name: 1-minute-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync new blocks
        run: |
          curl --request GET --url 'https://www.welding.app/api/sync'
      - name: Make invalidations
        run: |
          curl --request GET --url 'https://www.welding.app/api/invalidate'
